- hosts: homecloud
  remote_user: debian
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
    - vars/geerlingguy.security.yml
    - vars/geerlingguy.firewall.yml
  roles:
    # - { role: dev-sec.os-hardening }
    - { role: geerlingguy.security }
    - { role: geerlingguy.firewall }
    - { role: nickjj.docker }
    - { role: geerlingguy.ruby }
  tasks:    
  # Install packages
  - name: install htop
    apt:
      name: htop
      update_cache: yes
  - name: install vim
    apt:
      name: vim
      update_cache: yes
  - name: install rsync
    apt:
      name: rsync
      update_cache: yes
  - name: install python-setuptools
    apt:
      name: python-setuptools
      update_cache: yes
  - name: install git
    apt:
      name: git
      update_cache: yes
  - name: install fuse
    apt:
      name: fuse
      update_cache: yes
  # - cron:
  #     name: "backup postgres"
  #     minute: "0"
  #     hour: "2"
  #     job: "docker exec -it $(docker ps -a -q --filter ancestor=postgres --format={{ '{{.ID}}' }}) pg_dump -Upostgres nextcloud > /home/debian/`date +\\%d\\%m\\%y`_nextcloud.backup && cp /home/debian/`date +\\%d\\%m\\%y`_nextcloud.backup /home/debian/homecloud_storage/backups/db && rm /home/debian/`date +\\%d\\%m\\%y`_nextcloud.backup"
  # - cron:
  #     name: "backup nextcloud"
  #     minute: "30"
  #     hour: "2"
  #     job: "mkdir /home/debian/homecloud_storage/backups/nextcloud/`date +\\%d\\%m\\%y`_nextcloud && cp -rv volumes/nextcloud/config volumes/nextcloud/data volumes/nextcloud/themes homecloud_storage/backups/nextcloud/`date +\\%d\\%m\\%y`_nextcloud"
  - name: clone pip repo
    git:
      repo: https://github.com/pypa/pip
      dest: /usr/local/share/pip
  - name: install pip
    command: python setup.py install
    args:
      chdir: /usr/local/share/pip
  - name: install requests
    pip:
      name: requests==2.18.1
 # Configure traefik
  - name: Create acme.json if it doesn't exists
    file: 
      path: /home/debian/acme.json 
      state: touch 
      mode: '600'
  - name: copy traefik config
    copy:
      src: traefik.toml
      dest: /home/debian/traefik.toml
  # Mount OVH object storage as volume
  # - name: download ovh svfs package
  #   get_url:
  #     url: https://github.com/ovh/svfs/releases/download/v0.9.1/svfs_0.9.1_amd64.deb
  #     dest: /home/debian/svfs_0.9.1_amd64.deb
  # - name: install ovh svfs
  #   apt:
  #     deb: /home/debian/svfs_0.9.1_amd64.deb
  # - name: Creates directory homecloud_storage
  #   file: path=/home/debian/homecloud_storage state=directory
  # - name: copy openrc.sh
  #   copy:
  #     src: openrc.sh
  #     dest: /home/debian/openrc.sh
  # - name: mount volume
  #   shell: source /home/debian/openrc.sh && mount -t svfs -o username=$OS_USERNAME,password=$OS_PASSWORD,tenant=$OS_TENANT_NAME,region=$OS_REGION_NAME,storage_url=https://storage.sbg5.cloud.ovh.net/v1/AUTH_eb9248a4bc284392ac5a6c875fd694c0,container=homecloud homecloud /home/debian/homecloud_storage/
  #   args:
  #     executable: /bin/bash 
  #Docker
  - name: install docker
    pip:
      name: docker
  - name: install docker-compose
    pip:
      name: docker-compose
  - name: docker network create web
    command: docker network create web
    args:
      chdir: /home/debian
  - name: copy docker-compose file
    copy:
      src: docker-compose.yml
      dest: /home/debian/docker-compose.yml
  - name: docker compose down
    command: docker-compose down
    args:
      chdir: /home/debian
  - name: docker compose up
  
    command: docker-compose up -d
    args:
      chdir: /home/debian