version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=workaround
    volumes:
    - /home/debian/volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - common
  nextcloud:
    image: nextcloud
    restart: always
    environment:
        - POSTGRES_DB=nextcloud 
        - POSTGRES_USER=postgres 
        - POSTGRES_PASSWORD=secret
        - POSTGRES_HOST=db
        - NEXTCLOUD_ADMIN_USER=admin
        - NEXTCLOUD_ADMIN_PASSWORD=admin
    expose:
      - 80
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:cloud.mouillou.ch"
      - "traefik.enable=true"
      - "traefik.port=80"
    volumes:
    - /home/debian/volumes/nextcloud:/var/www/html
    networks:
      - common
    depends_on:
      - db
  reverse-proxy:
    image: traefik # The official Traefik docker image
    restart: always
    command: --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/debian/traefik.toml:/traefik.toml
      - /home/debian/acme.json:/acme.json
    container_name: traefik
networks:
  common:
  web:
    external: true